apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: regui
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip

spec:
  rules:
  - host: reg.csikoste.com
    http:
      paths:
      - path: /
        backend:
          serviceName: regui
          servicePort: http
