resources:
  - crd.yaml
  - deployment.yaml
  - hello.yaml
  - rbac.yaml

configMapGenerator:
- name: hello-controller-script
  files:
    - controller.sh

generatorOptions:
  disableNameSuffixHash: true
