apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: docker-registry
spec:
  chart: stable/docker-registry
  valuesContent: |
    ingress:
      enabled: true
      hosts:
        - docker-registry.self.signed
      tls:
        - secretName: docker-registry-tls
      annotations:
        traefik.ingress.kubernetes.io/redirect-entry-point: https
